// <auto-generated />
using System;
using Lancamentos.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Lancamentos.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(LancamentosDbContext))]
    partial class LancamentosDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Lancamentos.Dominio.Entidades.Lancamento", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento");

                    b.Property<DateTime>("RegistradoEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("registrado_em_utc");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("Id");

                    b.ToTable("lancamentos", (string)null);
                });

            modelBuilder.Entity("Lancamentos.Dominio.Entidades.OutboxMessage", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Conteudo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("conteudo");

                    b.Property<string>("CorrelacaoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlacao_id");

                    b.Property<DateTime>("OcorridaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrida_em_utc");

                    b.Property<DateTime?>("PublicadaEmUtc")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("publicada_em_utc");

                    b.Property<int>("TentativasPublicacao")
                        .HasColumnType("integer")
                        .HasColumnName("tentativas_publicacao");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("tipo");

                    b.Property<string>("UltimoErro")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("ultimo_erro");

                    b.HasKey("Id");

                    b.HasIndex("PublicadaEmUtc", "OcorridaEmUtc")
                        .HasDatabaseName("ix_outbox_messages_publicada_ocorrida");

                    b.ToTable("outbox_messages", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
