// <auto-generated />
using System;
using ConsolidadoDiario.Infraestrutura.Persistencia;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ConsolidadoDiario.Infraestrutura.Persistencia.Migrations
{
    [DbContext(typeof(ConsolidadoDiarioDbContext))]
    [Migration("20260317154016_InicialConsolidadoDiario")]
    partial class InicialConsolidadoDiario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ConsolidadoDiario.Dominio.Entidades.LancamentoProcessado", b =>
                {
                    b.Property<Guid>("LancamentoId")
                        .HasColumnType("uuid")
                        .HasColumnName("lancamento_id");

                    b.Property<string>("CorrelacaoId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("correlacao_id");

                    b.Property<DateOnly>("DataLancamento")
                        .HasColumnType("date")
                        .HasColumnName("data_lancamento");

                    b.Property<Guid>("EventoId")
                        .HasColumnType("uuid")
                        .HasColumnName("evento_id");

                    b.Property<DateTime>("Ocorrido")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("ocorrido_em_utc");

                    b.Property<DateTime>("Processado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("processado_em_utc");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("tipo");

                    b.Property<decimal>("Valor")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("valor");

                    b.HasKey("LancamentoId");

                    b.HasIndex("EventoId")
                        .HasDatabaseName("ix_lancamentos_processados_evento_id");

                    b.HasIndex("Processado")
                        .HasDatabaseName("ix_lancamentos_processados_processado_em_utc");

                    b.ToTable("lancamentos_processados", (string)null);
                });

            modelBuilder.Entity("ConsolidadoDiario.Dominio.Entidades.SaldoDiario", b =>
                {
                    b.Property<DateOnly>("Data")
                        .HasColumnType("date")
                        .HasColumnName("data");

                    b.Property<DateTime>("Atualizado")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("atualizado_em_utc");

                    b.Property<decimal>("Saldo")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("saldo");

                    b.Property<decimal>("TotalCreditos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_creditos");

                    b.Property<decimal>("TotalDebitos")
                        .HasPrecision(18, 2)
                        .HasColumnType("numeric(18,2)")
                        .HasColumnName("total_debitos");

                    b.HasKey("Data");

                    b.ToTable("saldos_diarios", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
